variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

stages:
  - plan
  - apply
  - authenticate
  - deploy

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

plan:
  stage: plan
  script:
    - /bin/sh .scripts/plan.sh
  artifacts:
    untracked: true

apply:
  stage: apply
  when: manual
  allow_failure: false
  needs: 
    - plan
  script:
    - /bin/sh .scripts/apply.sh
  only:
    - main

authenticate:
  stage: authenticate
  image: google/cloud-sdk:latest
  needs: 
    - apply
  script:
    - /bin/sh .scripts/authenticate.sh
  only:
    - main
  artifacts:
    untracked: true

deploy:
  stage: deploy
  needs: 
    - authenticate
  dependencies: 
    - authenticate
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - export KUBECONFIG=kube.conf
    - /bin/sh .scripts/k8s.sh
  only:
    - main2
