apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key-dns01
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.project }}
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json