name: kubernetes-gcp-infrastructure

on:
  push:
    branches:
      - master
      - main

jobs:
  kubernetes:
    name: "kubernetes deployment"
    runs-on: ubuntu-latest
    env:
      GCP_CI_SERVICE_KEY: ${{ secrets.GCP_CI_SERVICE_KEY }}
      CERT_MANAGER_KEY: ${{ secrets.CERT_MANAGER_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        run: |
          .scripts/plan.sh

      - name: apply
        run: |
          .scripts/apply.sh

      - name: authenticate
        run: |
          .scripts/authenticate.sh

      - name: deploy
        run: |
          export KUBECONFIG=kube.conf
          sed -i -e "s/{{CERT_MANAGER_KEY}}/${CERT_MANAGER_KEY}/" ./k8s/cert-manager-issuer/values.yaml
          .scripts/k8s.sh
